apiVersion: extensions/v1beta1  # v1 並無支援 Deployment 物件
kind: Deployment                # 指定類型為 Delopyment
metadata:
    name: demo         # 指定 deploy 名稱為 appworks-demo
spec:
  replicas: 1                   # 我只想開一台 pod 
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: wuchienhsin01/k8s-demo
        env:
        - name: SERVER_PORT
          value: "80"
        - name: DB_SERVER
          value: mongodb-svc
        ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec: 
  type: NodePort              # 叢集外部存取
  selector:
    app: demo        # 綁定 labels 為 app:appworks-demo 的 pod
  ports:
    - protocol: TCP
      port: 80